### ISSUE TITLE
Add required dependencies to the README

### ISSUE THREAD

**Issue by shinriyo** [SamuelGadiel/mason_cat#10]
**Description**

When using this brick, the generated code includes types from packages such as:

- `flutter_bloc`
- `dartz`
- `flutter_modular`

However, these are not listed in the README, which may confuse users who try to run the generated code and encounter missing package errors.

---

**Suggested Solution**

Please consider adding a section like:

```yaml
# Required dependencies (add to your pubspec.yaml)
dependencies:
  flutter_bloc: ^8.0.0
  dartz: ^0.10.1
  flutter_modular: ^5.0.3
```

Even better, linking to the versions used during the brick’s development would help avoid version conflicts.

---

**Why this matters**

- Helps new users get started quickly
- Prevents runtime and compile-time errors after generation
- Improves first impression and developer experience

Thanks for your work on this awesome brick!
